import { OnInit, OnDestroy, TemplateRef } from '@angular/core';
import { NzModalSubject } from './nz-modal-subject.service';
export declare class NzConfirmComponent implements OnInit, OnDestroy {
    subject: NzModalSubject;
    _prefixCls: string;
    _prefixConfirmCls: string;
    _maskClassMap: any;
    _bodyClassMap: any;
    _bodyStyleMap: any;
    _visible: boolean;
    _width: string;
    _zIndex: number;
    _iconTypeCls: string;
    _title: string;
    _titleTpl: TemplateRef<any>;
    _content: string;
    _maskClosable: boolean;
    _contentTpl: TemplateRef<any>;
    _okText: string;
    _cancelText: string;
    _animationStatus: string;
    _confirmLoading: boolean;
    _customClass: string;
    _typeCls: string;
    private contentEl;
    nzVisible: boolean;
    nzWidth: any;
    nzClass: string;
    nzZIndex: any;
    nzTitle: string | TemplateRef<any>;
    nzContent: string | TemplateRef<any>;
    nzMaskClosable: boolean;
    nzOkText: string;
    nzCancelText: string;
    nzIconType: string;
    nzConfirmType: string;
    nzConfirmLoading: boolean;
    onEsc(e: any): void;
    onEnter(e: any): void;
    setStyles(origin?: any): void;
    setClassMap(): void;
    anmiateFade(status: any): void;
    closeFromMask(e: any): void;
    constructor(subject: NzModalSubject);
    ngOnInit(): void;
    ngOnDestroy(): void;
}
