import { OnInit, EventEmitter, ElementRef, OnDestroy, TemplateRef, ComponentFactory, AfterViewInit, ViewContainerRef } from '@angular/core';
import { NzModalSubject } from './nz-modal-subject.service';
export declare class NzModalComponent implements OnInit, OnDestroy, AfterViewInit {
    subject: NzModalSubject;
    private _vcr;
    _prefixCls: string;
    _maskClassMap: any;
    _bodyClassMap: any;
    _bodyStyleMap: any;
    _visible: boolean;
    _confirmLoading: boolean;
    _closable: boolean;
    _width: string;
    _zIndex: number;
    _maskClosable: boolean;
    _title: string;
    _titleTpl: TemplateRef<any>;
    _content: string;
    _contentTpl: TemplateRef<any>;
    _footerTpl: TemplateRef<any>;
    _okText: string;
    _cancelText: string;
    _style: any;
    _wrapClass: string;
    _customClass: string;
    _animationStatus: string;
    _bodyComponent: ComponentFactory<any>;
    _componentParams: Object;
    _footerHide: boolean;
    modalId: string;
    contentEl: ElementRef;
    bodyEl: ViewContainerRef;
    nzVisible: boolean;
    nzConfirmLoading: boolean;
    nzClosable: boolean;
    nzClass: string;
    nzWidth: any;
    nzZIndex: any;
    nzTitle: string | TemplateRef<any>;
    nzContent: string | TemplateRef<any> | ComponentFactory<any>;
    nzFooter: TemplateRef<any> | boolean;
    nzOkText: string;
    nzCancelText: string;
    nzMaskClosable: boolean;
    nzStyle: Object;
    nzWrapClassName: string;
    nzComponentParams: Object;
    nzVisibleChange: EventEmitter<any>;
    nzOnOk: EventEmitter<any>;
    nzOnCancel: EventEmitter<any>;
    onEsc(e: any): void;
    setStyles(origin?: any): void;
    setClassMap(): void;
    anmiateFade(status: any): void;
    closeFromMask(e: any): void;
    setConfirmLoading(loading: boolean): void;
    open(): void;
    close(): void;
    clickOk(e: any): void;
    clickCancel(e: any): void;
    constructor(subject: NzModalSubject, _vcr: ViewContainerRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
}
