import { OnInit, OnDestroy, AfterViewInit, EventEmitter, ChangeDetectorRef } from '@angular/core';
import { NzMenuComponent } from './nz-menu.component';
import { Subject } from 'rxjs/Subject';
export declare class NzSubMenuComponent implements OnInit, OnDestroy, AfterViewInit {
    nzMenuComponent: NzMenuComponent;
    cd: ChangeDetectorRef;
    isInDropDown: boolean;
    level: number;
    _$mouseSubject: Subject<{}>;
    subMenus: any;
    nzOpen: boolean;
    nzOpenChange: EventEmitter<boolean>;
    readonly subItemSelected: boolean;
    readonly submenuSelected: boolean;
    clickSubMenuTitle(): void;
    clickSubMenuDropDown(): void;
    onMouseEnterEvent(e: any): void;
    onMouseLeaveEvent(e: any): void;
    readonly setDropDownSubmenuClass: boolean;
    readonly setMenuSubmenuOpenClass: boolean;
    readonly setDropDownVerticalClass: boolean;
    readonly setDropDownHorizontalClass: boolean;
    readonly setMenuSubmenuClass: boolean;
    readonly setMenuSubmenuSelectedClass: boolean;
    readonly setMenuVerticalClass: boolean;
    readonly setMenuHorizontalClass: boolean;
    readonly setMenuInlineClass: boolean;
    constructor(nzMenuComponent: NzMenuComponent, cd: ChangeDetectorRef);
    ngAfterViewInit(): void;
    ngOnInit(): void;
    ngOnDestroy(): void;
}
